title: Joseph Okpono
logo: Headshot.jpeg
description: Expert in transforming complex data into actionable insights and automating reports using Python, SQL, Excel, Tableau & Power BI, to drive strategic decision-making.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
