title: Joseph Okpono
logo: Data.jpeg
description: I am a data analysis with deep experience in analzying data using advance excel for report automation, and power Bi for business insight.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
